### ISSUE TITLE
Parsing of OH type Number not complete at startup (incomplete types.js)

### ISSUE THREAD

**Issue by Schluesselmeister** [ioBroker/ioBroker.openhab#10]
The object of OH are parsed at startup of the adapter. If an object of type "Number" is parsed, then the result is not complete as e.g. the item.label is not set.
Furthermore the categories provided by OH start with a capital letter.
With a modification as shown below the labels and roles are set correctly. I have added the "humidity" category also.

Regards,
 Sven

**Number definition (types.js)**

```
        var data = {
            name: item.label,
            type: 'number',
            read: true,
            write: false
        };
        if (item.stateDescription) {
            if (item.stateDescription.pattern && item.stateDescription.pattern.indexOf('°C') !== -1) {
                data.unit = '°C';
            }
            if (item.stateDescription.pattern && item.stateDescription.pattern.indexOf('°F') !== -1) {
                data.unit = '°F';
            }

            if ( (item.category === 'temperature' || item.category === 'Temperature') && item.stateDescription.readOnly === false) {
                data.role = 'level.temperature';
                data.write = true;
            } else if (item.category === 'temperature' || item.category === 'Temperature') {
                data.role = 'value.temperature';
            } else if (item.category === 'humidity' || item.category === 'Humidity') {
                data.role = 'value.humidity';
            }
        } else {
            if (item.category === 'temperature' || item.category === 'Temperature') {
                data.role = 'value.temperature';
            } else if (item.category === 'humidity' || item.category === 'Humidity') {
                data.role = 'value.humidity';
            }
        }

```

**Comment by Schluesselmeister** [comment]
Due to the other open issue #5, I have modified the types.h again.
It is not complete, as e.g. a switch might also be "readonly".
But that is the actual version of the file I have.

[types.zip](https://github.com/ioBroker/ioBroker.openhab/files/1524369/types.zip)

Regards,
 Sven

**Comment by Schluesselmeister** [comment]
Using the last version, which I have attached above, the SetPoint of a Thermostat can also be set. This should solve #5.

I will create a corresponding pull request.

Regards,
 Sven

**Comment by Apollon77** [comment]
Great!

**Comment by Schluesselmeister** [comment]
Modifications have been merged into the master branch,
