### ISSUE TITLE
oh2iob - Unknown type: quantity

### ISSUE THREAD

**Issue by jensfr1** [ioBroker/ioBroker.openhab#21]
Hi , i get the following message in the log. 
openhab.0 | 2018-12-10 17:26:12.388 | warn | oh2iob - Unknown type: quantity

**Comment by GermanBluefox** [comment]
@Schluesselmeister can you add it to adapter? I think it is number. :)

**Comment by Schluesselmeister** [comment]
@GermanBluefox I can try. At the moment I haven't running any ioBroker instance.
Please provide the item defintion. Which version of OH are you using?

**Comment by freifunkrothenburg** [comment]
Same issue for openhab 2.4 release. But for several types. Also it seems that the items get no update from openhab. I have to restart openhab adapter instance to update item status. 

What do you exactly need to debug

**Comment by Schluesselmeister** [comment]
OK, I have OH2.4 installed. I will have a look.

**Comment by Schluesselmeister** [comment]
Hi,
I have modified the main.js file. Unfortunatelly I cannot upload the file directly to the master branch.
@GermanBluefox : Would you be so kind to upload the file? I have  added support for "quantity", "call" and "stringlist" (at least reading the data). 
[main.zip](https://github.com/ioBroker/ioBroker.openhab/files/2715565/main.zip)

**Comment by GermanBluefox** [comment]
Fixed in https://github.com/ioBroker/ioBroker.openhab/commit/80146c692b7adbf8524eeeb49caf77e31e282331

**Comment by freifunkrothenburg** [comment]
@jensfr1
The missing updates seems to be an issue on OH side. So thank you for your investigation
