### ISSUE TITLE
Decimal type is parsed using parseInt instead of parseFloat

### ISSUE THREAD

**Issue by Schluesselmeister** [ioBroker/ioBroker.openhab#6]
The decimal type is converted using parseInt instead of parseFloat and therefore the number is truncated.
This is around line 566 of main.js.

It should look like:

if (value.type === 'DecimalType' || value.type === 'Decimal') {
  value.value = parseFloat(value.value);
} ...

**Comment by GermanBluefox** [comment]
Test https://github.com/ioBroker/ioBroker.openhab/commit/43b32fa707cc68a4c8ec533faf8ba9fbe4d26b8c

**Comment by Schluesselmeister** [comment]
Works as expected. Thanks.
